-- Prueba sin crear nada (WITH/CTE)
WITH
cfg AS (  -- simula CBRM_MX_REL_CONFIG_PYMT
  SELECT 18 AS ID_CONFIG_PYMT_PK,
         65509876678 AS ID_ACCOUNT_FK,
         DATE '2025-09-12' AS FCH_DEBIT_DATE
  FROM DUAL
),
p AS (    -- simula CBRM_MX_PRC_PYMTS
  SELECT 18 AS ID_CONFIG_PYMT_FK,
         '1875' AS ID_TXN_CODE,
         5000    AS IMP_TOTAL_AMOUNT,
         '10'    AS ID_PYMT_SEQ_PK,
         '7701'  AS COD_SUC_ORIG,
         '7701'  AS COD_SUC_OPER
  FROM DUAL
)
SELECT
  cfg.ID_ACCOUNT_FK AS CTA_ORDENANTE,
  p.ID_TXN_CODE     AS COD_OPER,
  p.IMP_TOTAL_AMOUNT AS COMISION_DIVISA,
  p.ID_PYMT_SEQ_PK  AS ID_DETALLE_COBR,
  p.COD_SUC_ORIG    AS CLAVE_SUC_ORIGEN,
  p.COD_SUC_OPER    AS CLAVE_SUC_OPERANTE
FROM p
JOIN cfg
  ON cfg.ID_CONFIG_PYMT_PK = p.ID_CONFIG_PYMT_FK
WHERE cfg.FCH_DEBIT_DATE >= TO_DATE('20250912','YYYYMMDD')
  AND cfg.FCH_DEBIT_DATE <  TO_DATE('20250912','YYYYMMDD') + 1
ORDER BY p.ID_PYMT_SEQ_PK;
