-- 1) (una sola vez) crea tablas temporales con solo las columnas que usas
CREATE GLOBAL TEMPORARY TABLE TMP_REL_CONFIG_PYMT (
  ID_CONFIG_PYMT_PK NUMBER,
  ID_ACCOUNT_FK     NUMBER,
  FCH_DEBIT_DATE    DATE
) ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE TMP_PRC_PYMTS (
  ID_CONFIG_PYMT_FK NUMBER,
  ID_TXN_CODE       VARCHAR2(10),
  IMP_TOTAL_AMOUNT  NUMBER,
  ID_PYMT_SEQ_PK    VARCHAR2(30),
  COD_SUC_ORIG      VARCHAR2(10),
  COD_SUC_OPER      VARCHAR2(10)
) ON COMMIT DELETE ROWS;

-- 2) Inserta datos de prueba
INSERT INTO TMP_REL_CONFIG_PYMT VALUES (18, 65509876678, DATE '2025-09-12');
INSERT INTO TMP_REL_CONFIG_PYMT VALUES (19, 65509876688, DATE '2025-09-13');

INSERT INTO TMP_PRC_PYMTS VALUES (18, '1875', 5000, '10', '7701', '7701');
INSERT INTO TMP_PRC_PYMTS VALUES (19, '0833',  400, '11', '7701', '7701');
INSERT INTO TMP_PRC_PYMTS VALUES (19, '0833',  120, '12', '7701', '7701');

-- 3) Ejecuta la misma consulta (apuntando a las TMP_*)
SELECT
  cfg.ID_ACCOUNT_FK AS CTA_ORDENANTE,
  p.ID_TXN_CODE     AS COD_OPER,
  p.IMP_TOTAL_AMOUNT AS COMISION_DIVISA,
  p.ID_PYMT_SEQ_PK  AS ID_DETALLE_COBR,
  p.COD_SUC_ORIG    AS CLAVE_SUC_ORIGEN,
  p.COD_SUC_OPER    AS CLAVE_SUC_OPERANTE
FROM TMP_PRC_PYMTS p
JOIN TMP_REL_CONFIG_PYMT cfg
  ON cfg.ID_CONFIG_PYMT_PK = p.ID_CONFIG_PYMT_FK
WHERE cfg.FCH_DEBIT_DATE >= TO_DATE('20250912','YYYYMMDD')
  AND cfg.FCH_DEBIT_DATE <  TO_DATE('20250912','YYYYMMDD') + 1
ORDER BY p.ID_PYMT_SEQ_PK;
