/* 1) Acumulados */
CREATE TABLE CBRM_MX_PRC_ACCUMULATED (
  ID_ACCUM_PK          NUMBER(17,0)   NOT NULL,
  NUM_ACCOUNT          VARCHAR2(34)   NOT NULL,       
  NUM_OPERATION_CODE   NUMBER(4,0),                   
  COD_OPERATION_CENTER VARCHAR2(10),                  
  IMP_AMOUNT_TXN       NUMBER(12,2)   DEFAULT 0 NOT NULL,
  NUM_VOLUME           NUMBER(36,0)   DEFAULT 0 NOT NULL,
  DSC_CHANNEL_NAME     VARCHAR2(50),                  
  DSC_DATASOURCE       VARCHAR2(50),                  
  FCH_ACCOUNTING       DATE,
  FCH_CREATION         DATE           DEFAULT SYSDATE,
  CONSTRAINT PK_CBRM_MX_PRC_ACCUMULATED PRIMARY KEY (ID_ACCUM_PK)
);

/* 2) Resumen */
CREATE TABLE CBRM_MX_PRC_SUMMARY (
  ID_SUMMARY_PK             NUMBER(17,0)  NOT NULL,
  ID_ACCUM_FK               NUMBER(17,0)  NOT NULL,   
  NUM_ACCOUNT               VARCHAR2(34)  NOT NULL,
  NUM_VOLUME                NUMBER(36,0)  DEFAULT 0,
  ID_RULE_FK                NUMBER(10,0),
  ID_REL_PR_LI_PRODUCT_FK   NUMBER(17,0),
  NUM_RANGE_MIN             NUMBER(36,0),
  NUM_RANGE_MAX             NUMBER(36,0),
  IMP_PRICE                 NUMBER(12,2),
  VAL_FEE_TYPE              VARCHAR2(50),
  ID_BILL_FK                NUMBER(17,0),
  FCH_ACCOUNTING            DATE,
  FCH_CREATION              DATE          DEFAULT SYSDATE,
  CONSTRAINT PK_CBRM_MX_PRC_SUMMARY PRIMARY KEY (ID_SUMMARY_PK)
);

/* 3) Pagos (solicitud/respuesta) */
CREATE TABLE CBRM_MX_PRC_PYMTS (
  ID_PYMT_SEQ_PK     NUMBER(17,0)  NOT NULL,
  ID_ACCUM_FK        NUMBER(17,0)  NOT NULL,
  ID_BILL_FK         NUMBER(17,0)  NOT NULL,
  ID_CONFIG_PYMT_FK  NUMBER(10,0),
  ID_RULE_FK         NUMBER(10,0),
  ID_TNX_CODE        NUMBER(4,0),
  IMP_TOTAL_AMOUNT   NUMBER(12,2),
  ID_TNX_CODE_VAT    NUMBER(4,0),
  IMP_VAT            NUMBER(12,2),
  IMP_FEE_CHARGE     NUMBER(12,2),
  IMP_AMOUNT_PENDING NUMBER(12,2),
  IMP_FINAL_CHARGE   NUMBER(12,2),
  VAL_PYMT_STATUS    VARCHAR2(50),
  NUM_MOV_COMIS      NUMBER(9,0),
  NUM_MOV_VAT        NUMBER(9,0),
  COD_SUC_ORIG       VARCHAR2(4),
  COD_SUC_OPER       VARCHAR2(4),
  DESC_OBS           VARCHAR2(150),
  ID_ARCHIVE         VARCHAR2(20),
  COD_ERROR          VARCHAR2(50),
  FCH_CREATION       DATE          DEFAULT SYSDATE,
  CONSTRAINT PK_CBRM_MX_PRC_PYMTS PRIMARY KEY (ID_PYMT_SEQ_PK)
);

/* 4) Facturas (concentrado) */
CREATE TABLE CBRM_MX_PRC_BILL (
  ID_BILL_PK         NUMBER(17,0)   NOT NULL,
  ID_CONFIG_PYMT_FK  NUMBER(10,0),
  NUM_ACCOUNT        VARCHAR2(34),
  DSC_LEGAL_NAME     VARCHAR2(150),
  NUM_CHARGE_ACC     VARCHAR2(34),
  VAL_CCY            VARCHAR2(3),
  VAL_CHARGE_TYPE    VARCHAR2(50),
  IMP_TOTAL_AMNT     NUMBER(12,2),
  VAL_PYMT_STATUS    VARCHAR2(50),
  FCH_BILLED_DT      DATE,
  ID_CHARGE_STATUS   VARCHAR2(1),
  FCH_CREATION       DATE           DEFAULT SYSDATE,
  CONSTRAINT PK_CBRM_MX_PRC_BILL PRIMARY KEY (ID_BILL_PK)
);

/* 5) Cargos de comisión */
CREATE TABLE CBRM_MX_PRC_COMMISS_CHARGE (
  ID_COMMISS_CHARGE_PK NUMBER(17,0) NOT NULL,
  ID_CONFIG_PYMT_FK    NUMBER(10,0),
  NUM_CHARGE_ACC       VARCHAR2(34),
  VAL_CHARGE_TYPE      VARCHAR2(50),
  VAL_EXCH_RATE        NUMBER(12,6),
  DSC_CONCEPT          VARCHAR2(150),
  VAL_TNX_CODE         NUMBER(4,0),
  IMP_FINAL_CHARGE     NUMBER(12,2),
  VAL_CCY              VARCHAR2(3),
  VAL_PYMT_STATUS      VARCHAR2(50),
  ID_BILL_FK           NUMBER(17,0),
  FCH_OPERATION        DATE,
  CONSTRAINT PK_CBRM_MX_PRC_COMMISS_CH PRIMARY KEY (ID_COMMISS_CHARGE_PK)
);

/* 6) Reporte de factura (salida para PDF/Excel) */
CREATE TABLE CBRM_MX_PRC_INVOICE_RPRT (
  ID_BILL_FK        NUMBER(17,0)  NOT NULL,
  NUM_CHARGE_ACC    VARCHAR2(34),
  VAL_ACC_CCY       VARCHAR2(3),
  ID_CUSTOMER_FK    NUMBER(10,0),
  DSC_LEGAL_NAME    VARCHAR2(150),
  DSC_PRICE_LIST    VARCHAR2(100),
  DSC_PRODUCT_NAME  VARCHAR2(150),
  DSC_CHANNEL       VARCHAR2(50),
  DSC_FEE_TYPE      VARCHAR2(50),
  FCH_TXN_START_DT  DATE,
  FCH_TXN_END_DT    DATE,
  NUM_RANGE_MIN     NUMBER(36,0),
  NUM_RANGE_MAX     NUMBER(36,0),
  IMP_PRICE         NUMBER(12,2),
  NUM_VOLUME        NUMBER(36,0),
  IMP_AMOUNT        NUMBER(12,2),
  VAL_EXCH_RATE     NUMBER(12,6),
  IMP_TOTAL_AMOUNT  NUMBER(12,2),
  IMP_VAT           NUMBER(12,2),
  IMP_FINAL_CHARGE  NUMBER(12,2),
  FCH_BILLED_DT     DATE,
  VAL_PYMT_STATUS   VARCHAR2(50)
);

/* 7) Bitácora de proceso (control archivos/proceso) */
CREATE TABLE CBRM_MX_PRC_PROCESS_LOG (
  ID_PROCESS_LOG_PK  NUMBER(17,0)  NOT NULL,
  TXT_OUT_FILENAME   VARCHAR2(255),
  TXT_SENDING_STATUS VARCHAR2(50),
  TXT_IN_FILENAME    VARCHAR2(255),
  TXT_REQST_STATUS   VARCHAR2(50),
  CONSTRAINT PK_CBRM_MX_PRC_PROCESS_LOG PRIMARY KEY (ID_PROCESS_LOG_PK)
);
